### PR TITLE
Return Node externalIP

### PR DESCRIPTION
**Pull request by imharshita**
Signed-off-by: Harshita sharma <harshita.sharma6174@gmail.com>

**What this PR does / why we need it**: 
- Fetches external IP of all nodes so that collector can use them to fetch the master location
-  Adds a method to set the master location in the report

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by imharshita** [comment]
@lsviben ptal

**Comment by lsviben** [comment]
I am wondering if we could just get the node external IP in the kubernetes agent collect phase : https://github.com/kubermatic/telemetry-client/blob/3a7182a21e2f14580c0e4066f7e2110610aa960a/pkg/agent/kubernetes/v1/agent.go#L101

It seems more natural to get it there as we already have the client, and node data, instead of creating the client and getting node data again in the report phase.

Then in the collector we can just get the external IP from one of the nodes in the report and get the location data.

**Comment by imharshita** [comment]
> I am wondering if we could just get the node external IP in the kubernetes agent collect phase :
> 
> https://github.com/kubermatic/telemetry-client/blob/3a7182a21e2f14580c0e4066f7e2110610aa960a/pkg/agent/kubernetes/v1/agent.go#L101
> 
> It seems more natural to get it there as we already have the client, and node data, instead of creating the client and getting node data again in the report phase.
> 
> Then in the collector we can just get the external IP from one of the nodes in the report and get the location data.

Done. But not fetching external-ip for all nodes, just one.

**Pull request merged**
